FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
mysql-client \
python3 \
python3-pip \
ruby2.7 \
wget \
apt-transport-https \
software-properties-common
RUN pip3 install -U V